// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mvrnormArma
arma::mat mvrnormArma(int n, arma::vec mu, arma::mat sigma);
RcppExport SEXP _gmJenkins_mvrnormArma(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvrnormArma(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// pnorm_arma
arma::vec pnorm_arma(arma::vec x);
RcppExport SEXP _gmJenkins_pnorm_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pnorm_arma(x));
    return rcpp_result_gen;
END_RCPP
}
// dprobit_rcpp
arma::vec dprobit_rcpp(arma::vec b, Rcpp::List data_list);
RcppExport SEXP _gmJenkins_dprobit_rcpp(SEXP bSEXP, SEXP data_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data_list(data_listSEXP);
    rcpp_result_gen = Rcpp::wrap(dprobit_rcpp(b, data_list));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gmJenkins_mvrnormArma", (DL_FUNC) &_gmJenkins_mvrnormArma, 3},
    {"_gmJenkins_pnorm_arma", (DL_FUNC) &_gmJenkins_pnorm_arma, 1},
    {"_gmJenkins_dprobit_rcpp", (DL_FUNC) &_gmJenkins_dprobit_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_gmJenkins(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
