# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_gmJenkins_mvrnormArma`, n, mu, sigma)
}

pnorm_arma <- function(x) {
    .Call(`_gmJenkins_pnorm_arma`, x)
}

dprobit_rcpp <- function(b, data_list) {
    .Call(`_gmJenkins_dprobit_rcpp`, b, data_list)
}

